### Imports

In [1]:
from pathlib import Path
import pandas as pd

from src.config import RAW_PDF_DIR
from src.ingest.pdf_parser import (
    pdf_to_text,
    extract_report_week,
    find_all_district_rows,
    parse_wer_pdf,
    CANONICAL_RDHS
)

pdf_files = sorted(RAW_PDF_DIR.glob('*.pdf'))
print("PDFs: ", len(pdf_files))

PDFs:  1017

### Check a sample video

In [2]:
sample_files = []

sample_files.append(pdf_files[0])

for fraction in [0.2,0.4,0.6,0.8]:
    index = int(len(pdf_files) * fraction)
    sample_files.append(pdf_files[index])

sample_files.append(pdf_files[-1])
sample_files = list(dict.fromkeys(sample_files))

for path in sample_files:
    print(path.name)

wer_2007_w01.pdf
wer_2010_w47.pdf
wer_2014_w42.pdf
wer_2018_w37.pdf
wer_2022_w31.pdf
wer_2026_w27.pdf

### Inspect the first PDF

In [3]:
pdf_path = sample_files[4]

print(pdf_path)

text = pdf_to_text(pdf_path)

print(text[:100000])

/media/breezy/NewVolume/projects_int/dengue/data/raw/wer_pdfs/wer_2022_w31.pdf
                       WEEKLY EPIDEMIOLOGICAL REPORT
                                 A publication of the Epidemiology Unit
                          Ministry of Health, Nutrition & Indigenous Medicine
                                      231, de Saram Place, Colombo 01000, Sri Lanka
                          Tele: + 94 11 2695112, Fax: +94 11 2696583, E mail: epidunit@sltnet.lk
                                 Epidemiologist: +94 11 2681548, E mail: chepid@sltnet.lk
                                               Web: http://www.epid.gov.lk


                  Vol. 49 No. 31                                                                      30 th– 05th Aug 2022
 SRI LANKA 2022
                                           Can we eliminate Tuberculosis? Part II
                  This is the last article of series of two arti-        If yes, how?
                  cles.                                                  INTEGRATED,                  PATIENT-CENTRED
                  According to the WHO estimates, 14,000                 CARE AND PREVENTION is composed of
                  cases should be notified each year. It is              2 objectives according to the NTP 2021-
                  slightly decreased towards this number                 2025. The first one is “To find and success-
                  after 2000. Is this estimation correct? If so,         fully treat, on average, between 2021 and
                  we lack nearly 5000 cases each year and                2025, 10,000 cases of drug-sensitive TB
                  6000 in 2020. Is there that amount of unde-            annually, including 600 children”
                  tected or missed cases in our community?               Steps that should be taken for active case
                  Or has the WHO overestimated it? If it is,             detection.
                  the decline in the number of TB cases is                      Increasing the awareness of Tuber-
                  justified by the following factors.                            culosis among patients and health
                         The constant decline of smear-                         care workers.
                          positive TB cases.                              “Cough more than two weeks” is the cardi-
                         TB cases at the young age groups                    nal feature we look in to suspect TB in
                          are drastically declined and age dis-               one.         That information should be
                          tribution has deviated to the old age               gone to both the community and
                          groups.                                             HCWs. Then people will actively ap-
                         Routine notification data are tallied               proach by seeking health care assis-
                          between national and sub-national                   tance when they have a cough for
                          levels.                                             more than 2 weeks. Doctors and nurs-
WER


                  We have partly achieved the objectives of                   es will enthusiastically look for people
                  the national TB strategic plan 2015-2020.                   compatible with TB in OPD and inward
                  Now we have adhered to the newest strat-                    settings and refer them for further in-
                  egy 2010-2025 to achieve universal access                   vestigations of TB.
                  to TB diagnosis and treatment by 2025 and                     Contact tracing of pulmonary TB
                  get on track to achieve the End TB targets                     patients, to find latent TB and active
                  by 2035. Is it possible even with the eco-                     TB cases.
                  nomic crisis and Covid pandemic we are                        Launching TB detection campaigns
                  facing to?                                                     targeting high-risk groups.
                                                                                Screening of HIV patients

                      Contents                                                                                      Page
                      1. Can we eliminate Tuberculosis? Part II                                                     1
                      2. Summary of selected notifiable diseases reported (23rd – 29th July 2022 )                  3
                      3. Surveillance of vaccine preventable diseases & AFP (23rd – 29th July 2022)                 4
WER Sri Lanka - Vol. 49 No. 31                                                                       30th– 05th Aug 2022
       Use advanced and extensive diagnosis methods –         Lanka, health facility is available free of charge and most
        TB culture, WRD Gene X-perts, Histology                TB cases are detected through the government health
                                                               sector. DOT provision, sputum microscopy, and all other
Steps that should be taken for successful treatment out-       management of TB patients are conducted through dis-
come.                                                          trict chest clinics and other regional focal points estab-
       DOT strategy (direct observation of therapy) –         lished by the government. Anyhow, we should continue
        treatment adherence is crucial to cure TB and          the strategy to reduce the TB –related burden. Using this
        avoid the emergence of drug resistance. Patients       amount of budget for TB control is justifiable rather than
        take their pills in front of the DOT provider. Hence   spending them for treating a large amount of TB pa-
        make sure the best possible outcome for the pa-        tients. Then we can move to a new low-cost strategic
        tient through integrity.                               plan in 2025 after achieving targeted milestones. So, this
       Retrieval mechanism for defaulters – Look for de-      is still possible if we can get more funds.
        faulters actively and recruit them back for DOT.       Other challenges ahead in the path of TB elimination
       Support patients to cope with drug side effects.       are,
       By the above means, we can interrupt the chain of              Drug addiction
        transmission.                                                  Poverty
                                                                       Overpopulation in TB hotspots
Other steps to prevent TB                                              Lack of awareness in health care workers and the
                                                                        community
       Infection control - standard precautions, ad-                  Defaulting of treatments by patients
        ministrative controls, environment control,                    Diabetes mellitus
        infrastructure for effective infection control,                HIV and MDR TB are not the issues with a big
        personnel protective equipment                                  gravity in Sri Lanka.
       BCG vaccination
       Chemo prophylaxis                                      Compiled By,
                                                              Dr.V.U. Jayasinghe
Budget for national TB strategic plan 2021-2025                MBBS, Diploma in Tuberculosis and Chest Medicine.
The total cost of this plan is US$ 29.81million. This
amount will be divided unequally among the different           References
objectives of the plan. 60.2% of this is allocated for in-            https://www.nptccd.health.gov.lk/wp-content/

tensified case detection and prompt treatment. The next                   uploads/2022/02/NSP-NPTCCD-2021-25.pdf
                                                                      https://www.who.int/teams/global-tuberculosis-programme/
highest allocation is for the 6th objective. That is to im-
                                                                          tb-reports
prove the efficiency and effectiveness of this manage-
                                                                      https://www.nptccd.health.gov.lk/wp-content/
ment and organization of TB control activities. And, to
                                                                          uploads/2022/03/NPTCCD-Annual-Report-2020.pdf
expend on the salary of NTP staff and training sessions.              https://www.atsjournals.org/doi/full/10.1164/rccm.201809-
US$ 14.7 million of the total cost will be supplied by the                1623ED
government of Sri Lanka and US$5.685 million will be                  https://data.worldbank.org/indicator/SH.TBS.CURE.ZS?
supplied by the Global fund. The budget gap of 7.543 is                   locations=8S
supposed to be picked up by other donors like the World               https://www.who.int/docs/default-source/searo/

Bank, WHO, and SAARC.                                                     tuberculosis/rglc-report-sri-lanka-2019-july.pdf?
                                                                          sfvrsn=6ef508f7_2
Currently, Sri Lanka is facing the worst economic crisis
                                                                      https://disease.lk/tuberculosis/
ever met in recent decades. Therefore, such a big allo-
                                                                      http://www.nptccd.health.gov.lk/wp-content/
cation for the TB program could not be realistic. In that
                                                                          uploads/2019/11/NSP-Sri-Lanka.pdf
case, we may have to find more foreign funds. In Sri

 Page 2
         RDHS               Dengue Fever Dysentery Encephaliti Enteric Fever Food Poi-                                    Leptospirosis          Typhus             Viral Hep-       Human            Chickenpox         Meningitis          Leishmania-        WRCD
                            A       B            A       B        A       B        A       B           A       B          A        B             A        B         A       B        A       B        A       B          A       B           A       B          T*        C**
         Colombo              38        8215         0        4       0        3       0          0        0         5         2        112           0         0       0        3       0        0       2        19        0          7        0          2      14        97

         Gampaha              17        4803         0        5       0        1       0          0        0        12         4          95          0         0       0        8       0        3       1        28        1         26        0        28         5       76

         Kalutara             17        2560         1       12       0        1       0          1        0         6        17        235           0         3       0        2       0        2       7        46        0         17        0          2        3 100

         Kandy                23        2904         3       15       0        0       0          2        1         5         8        103           2        25       0        8       0        0       5        42        1          6        1        17       12 100

         Matale               36         669         0        2       0        0       0          0        0         0         1          73          0         3       0        2       0        0       2        15        0          1        4       203       17 100

         NuwaraEliya            9        152         1       15       0        0       0          2        0         1         0          49          0        12       0        4       0        0       0        26        1          3        0          0      23        98

         Galle                15        2582         0        7       0        0       0          0        0         0         7        272           1        13       0        2       0        0       1        47        0         13        0          0      11 100

         Hambantota           76         972         0       24       0        0       0          0        0         2         5        148           4        30       0        4       0        0       0        19        0          6     15         304       16        97
                                                                                                                                                                                                                                                                                                                                                                   WER Sri Lanka - Vol. 49 No . 31




         Matara               59        1063         1       12       1        2       0          0        0         0         4        164           0         8       0        1       0        0       0        25        0          6        0       176       28 100

         Jaffna               46        2324         4       41       0        2       1         57        0        27         0          19          0       408       0        6       0        4       1        73        1         10        0          0      64        88

         Kilinochchi            1          93        0        6       0        0       0          1        0        21         0          11          0         9       0        0       0        0       0          4       0          1        0          2      31        98

         Mannar                 1        174         1        2       0        0       0          0        0         0         0          18          0         3       0        2       0        0       1          6       0         15        0          0      19        81

         Vavuniya               0          66        1        3       0        1       0          2        0         0         1          15          0         1       0        0       0        0       2        14        0          0        0          4        2       99

         Mullaitivu             1          47        0        4       0        0       0          2        0         3         0          23          0         5       0        0       0        0       0          6       0          1        0          1      21        94

         Batticaloa             8        966         0       44       0        7       0          0        0        20         0          29          0         0       0        1       0        1       0        15        0         25        0          1      36 100

         Ampara                 4        123         1       10       0        1       0          0        0        17         0          76          0         1       0        1       0        0       0        35        0         16        0        12         9       96

         Trincomalee            1        973         0       22       0        0       0          1        0         2         0          20          0         3       0        4       0        0       0        32        0          6        0          1      17        85

         Kurunegala           61        1869         1       14       0        1       0          0        0         4         5          98          2        20       0        0       0        1       2        40        0         22     14         316         9       97
                                                                                                                                                                                                                                                                                    Table 1: Selected notifiable diseases reported by Medical Officers of Health




         Puttalam             36        1378         0        3       0        0       0          0        0         0         0          19          0         7       0        0       0        0       1          8       0         21        0          4      15        91

         Anuradhapur          25         290         0        8       0        2       0          1        0         5         0        122           0        19       0        2       0        1       1        37        1         29        8       259         8       89

         Polonnaruwa            7        101         0        5       0        0       0          0        0         1         5          90          0         0       0        3       0        0       1        10        0          3     14         281       15        96

         Badulla              36         732         1       14       0        1       0          1        0         5        11        139           2        33       3       91       0        0       0        38        0         11        1        16       14 100

         Monaragala           11         308         0        6       0        1       0          4        0         2         2        213           0        20       3       37       0        0       0        37        2         34        1        89       11 100

         Ratnapura            13        1941         1       30       0        6       0          3        0        26        27        636           2        18       0       17       0        0       2        52        4         42     17         140       12        95

         Kegalle              11        1698         1       12       0        5       0          1        0         5         4        337           1        15       0        4       0        0       1        62        0         34        0        15         8       99

         Kalmune              28         704         0       24       0        0       0          1        0         6         0          16          0         1       0        1       0        0       1        36        5         28        0          0      29 100
         SRILANKA            18 37707 17 344                          1       34       1        79         1       175     10          3132          14   657           6    20          0       12   31          772     16         383 75           1873         17        94
                                                                                                                                                                                                                                                                                    23rd– 29th Jul 2022 (30th Week)
                                                                                                                                                                                                                                                                                                                                                                     30th– 05th Aug 2022




Page 3
         Source: Weekly Returns of Communicable Diseases (esurvillance.epid.gov.lk). T=Timeliness refers to returns received on or before 29th July , 2022 Total number of reporting units 361 Number of reporting units data provided for the current week: 314 C**-Completeness
                                                                                                                                             *
WER Sri Lanka - Vol. 48 No. 31                                                                                                      30th– 05th Aug 2022
Table 2: Vaccine-Preventable Diseases & AFP                                                                             23rd– 29th Jul 2022 (30th Week)

### Test report date extraction

In [4]:
rows = find_all_district_rows(text)

print(
    "Districts found:",
    len(rows)
)

for district in CANONICAL_RDHS:

    values = rows.get(district)

    if values is None:
        print(
            f"{district:20} MISSING"
        )
    else:
        print(
            f"{district:20} "
            f"numbers={len(values):2d} "
            f"first_values={values[:8]}"
        )

Districts found: 26
Colombo              numbers=26 first_values=[38, 8215, 0, 4, 0, 3, 0, 0]
Gampaha              numbers=26 first_values=[17, 4803, 0, 5, 0, 1, 0, 0]
Kalutara             numbers=26 first_values=[17, 2560, 1, 12, 0, 1, 0, 1]
Kandy                numbers=26 first_values=[23, 2904, 3, 15, 0, 0, 0, 2]
Matale               numbers=26 first_values=[36, 669, 0, 2, 0, 0, 0, 0]
Nuwara Eliya         numbers=26 first_values=[9, 152, 1, 15, 0, 0, 0, 2]
Galle                numbers=26 first_values=[15, 2582, 0, 7, 0, 0, 0, 0]
Matara               numbers=26 first_values=[59, 1063, 1, 12, 1, 2, 0, 0]
Hambantota           numbers=26 first_values=[76, 972, 0, 24, 0, 0, 0, 0]
Jaffna               numbers=26 first_values=[46, 2324, 4, 41, 0, 2, 1, 57]
Kilinochchi          numbers=26 first_values=[1, 93, 0, 6, 0, 0, 0, 1]
Mannar               numbers=26 first_values=[1, 174, 1, 2, 0, 0, 0, 0]
Vavuniya             numbers=26 first_values=[0, 66, 1, 3, 0, 1, 0, 2]
Mullaitivu           numbers=26 first_values=[1, 47, 0, 4, 0, 0, 0, 2]
Batticaloa           numbers=26 first_values=[8, 966, 0, 44, 0, 7, 0, 0]
Ampara               numbers=26 first_values=[4, 123, 1, 10, 0, 1, 0, 0]
Trincomalee          numbers=26 first_values=[1, 973, 0, 22, 0, 0, 0, 1]
Kalmunai             numbers=26 first_values=[28, 704, 0, 24, 0, 0, 0, 1]
Kurunegala           numbers=26 first_values=[61, 1869, 1, 14, 0, 1, 0, 0]
Puttalam             numbers=26 first_values=[36, 1378, 0, 3, 0, 0, 0, 0]
Anuradhapura         numbers=26 first_values=[25, 290, 0, 8, 0, 2, 0, 1]
Polonnaruwa          numbers=26 first_values=[7, 101, 0, 5, 0, 0, 0, 0]
Badulla              numbers=26 first_values=[36, 732, 1, 14, 0, 1, 0, 1]
Monaragala           numbers=26 first_values=[11, 308, 0, 6, 0, 1, 0, 4]
Ratnapura            numbers=26 first_values=[13, 1941, 1, 30, 0, 6, 0, 3]
Kegalle              numbers=26 first_values=[11, 1698, 1, 12, 0, 5, 0, 1]

### import

In [5]:
from pathlib import Path

import pandas as pd

from src.config import (
    DENGUE_BRONZE_PATH,
    DENGUE_SILVER_PATH,
)

from src.cleaning.dengue_cleaner import (
    clean_dengue_panel,
    create_complete_panel,
)

from src.cleaning.validation import (
    validate_panel,
    print_validation_report,
)

### read the dataset

In [6]:
raw = pd.read_parquet(
    DENGUE_BRONZE_PATH
)

raw.head()

,district,source_file,week_ending,epi_week,year,dengue_fever_this_week,dengue_fever_cumulative,dysentery_this_week,dysentery_cumulative,encephalitis_this_week,...,meningitis_this_week,meningitis_cumulative,leishmaniasis_this_week,leishmaniasis_cumulative,timeliness_pct,completeness_pct,tuberculosis_this_week,tuberculosis_cumulative,leprosy_this_week,leprosy_cumulative
0,Colombo,wer_2007_w01.pdf,2006-12-29,52,2006,71,3419,2,356,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Gampaha,wer_2007_w01.pdf,2006-12-29,52,2006,12,1774,0,331,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Kalutara,wer_2007_w01.pdf,2006-12-29,52,2006,12,977,6,506,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Kandy,wer_2007_w01.pdf,2006-12-29,52,2006,20,1509,5,452,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Matale,wer_2007_w01.pdf,2006-12-29,52,2006,4,389,0,344,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
print(
    raw.shape
)

print(
    raw.columns.tolist()
)

(26441, 36)
['district', 'source_file', 'week_ending', 'epi_week', 'year', 'dengue_fever_this_week', 'dengue_fever_cumulative', 'dysentery_this_week', 'dysentery_cumulative', 'encephalitis_this_week', 'encephalitis_cumulative', 'enteric_fever_this_week', 'enteric_fever_cumulative', 'food_poisoning_this_week', 'food_poisoning_cumulative', 'leptospirosis_this_week', 'leptospirosis_cumulative', 'typhus_this_week', 'typhus_cumulative', 'viral_hepatitis_this_week', 'viral_hepatitis_cumulative', 'returns_pct', 'human_rabies_this_week', 'human_rabies_cumulative', 'chickenpox_this_week', 'chickenpox_cumulative', 'meningitis_this_week', 'meningitis_cumulative', 'leishmaniasis_this_week', 'leishmaniasis_cumulative', 'timeliness_pct', 'completeness_pct', 'tuberculosis_this_week', 'tuberculosis_cumulative', 'leprosy_this_week', 'leprosy_cumulative']

### clean the dengue panel

In [8]:
clean = clean_dengue_panel(
    raw
)

clean.head()

[clean] drop unparseable year/week: 26441 → 26441 rows (Δ 0)
[clean] filter weeks 1-54: 26441 → 26441 rows (Δ 0)
[clean] filter canonical districts: 26441 → 26441 rows (Δ 0)
[clean] drop null week_start: 26441 → 26441 rows (Δ 0)

[WARNING] Duplicate district/week observations detected (104 rows):
    district  year  week week_start      source_file  cases
      Ampara  2016    53 2017-01-02 wer_2016_w53.pdf      0
      Ampara  2017     1 2017-01-02 wer_2017_w01.pdf      5
      Ampara  2021    53 2022-01-03 wer_2021_w53.pdf      1
      Ampara  2022     1 2022-01-03 wer_2022_w01.pdf      2
Anuradhapura  2016    53 2017-01-02 wer_2016_w53.pdf      7
Anuradhapura  2017     1 2017-01-02 wer_2017_w01.pdf     16
Anuradhapura  2021    53 2022-01-03 wer_2021_w53.pdf     13
Anuradhapura  2022     1 2022-01-03 wer_2022_w01.pdf     13
     Badulla  2016    53 2017-01-02 wer_2016_w53.pdf     18
     Badulla  2017     1 2017-01-02 wer_2017_w01.pdf     40
     Badulla  2021    53 2022-01-03 wer_2021_w53.pdf     78
     Badulla  2022     1 2022-01-03 wer_2022_w01.pdf     78
  Batticaloa  2016    53 2017-01-02 wer_2016_w53.pdf     17
  Batticaloa  2017     1 2017-01-02 wer_2017_w01.pdf     43
  Batticaloa  2021    53 2022-01-03 wer_2021_w53.pdf     25
  Batticaloa  2022     1 2022-01-03 wer_2022_w01.pdf     25
     Colombo  2016    53 2017-01-02 wer_2016_w53.pdf    547
     Colombo  2017     1 2017-01-02 wer_2017_w01.pdf    511
     Colombo  2021    53 2022-01-03 wer_2021_w53.pdf     40
     Colombo  2022     1 2022-01-03 wer_2022_w01.pdf     40
       Galle  2016    53 2017-01-02 wer_2016_w53.pdf     79
       Galle  2017     1 2017-01-02 wer_2017_w01.pdf    176
       Galle  2021    53 2022-01-03 wer_2021_w53.pdf     44
       Galle  2022     1 2022-01-03 wer_2022_w01.pdf     44
     Gampaha  2016    53 2017-01-02 wer_2016_w53.pdf     44
     Gampaha  2017     1 2017-01-02 wer_2017_w01.pdf    137
     Gampaha  2021    53 2022-01-03 wer_2021_w53.pdf     43
     Gampaha  2022     1 2022-01-03 wer_2022_w01.pdf     43
  Hambantota  2016    53 2017-01-02 wer_2016_w53.pdf     26
  Hambantota  2017     1 2017-01-02 wer_2017_w01.pdf     31
  Hambantota  2021    53 2022-01-03 wer_2021_w53.pdf     25
  Hambantota  2022     1 2022-01-03 wer_2022_w01.pdf     25
      Jaffna  2016    53 2017-01-02 wer_2016_w53.pdf     57
      Jaffna  2017     1 2017-01-02 wer_2017_w01.pdf    145
      Jaffna  2021    53 2022-01-03 wer_2021_w53.pdf     74
      Jaffna  2022     1 2022-01-03 wer_2022_w01.pdf     74
    Kalmunai  2016    53 2017-01-02 wer_2016_w53.pdf     21
    Kalmunai  2017     1 2017-01-02 wer_2017_w01.pdf     90
    Kalmunai  2021    53 2022-01-03 wer_2021_w53.pdf     10
    Kalmunai  2022     1 2022-01-03 wer_2022_w01.pdf     10
    Kalutara  2016    53 2017-01-02 wer_2016_w53.pdf     77
    Kalutara  2017     1 2017-01-02 wer_2017_w01.pdf     88
    Kalutara  2021    53 2022-01-03 wer_2021_w53.pdf     20
    Kalutara  2022     1 2022-01-03 wer_2022_w01.pdf     20
       Kandy  2016    53 2017-01-02 wer_2016_w53.pdf     67
       Kandy  2017     1 2017-01-02 wer_2017_w01.pdf     66
       Kandy  2021    53 2022-01-03 wer_2021_w53.pdf     72
       Kandy  2022     1 2022-01-03 wer_2022_w01.pdf     72
     Kegalle  2016    53 2017-01-02 wer_2016_w53.pdf     22
     Kegalle  2017     1 2017-01-02 wer_2017_w01.pdf     34
     Kegalle  2021    53 2022-01-03 wer_2021_w53.pdf     42
     Kegalle  2022     1 2022-01-03 wer_2022_w01.pdf     42
 Kilinochchi  2016    53 2017-01-02 wer_2016_w53.pdf      8
 Kilinochchi  2017     1 2017-01-02 wer_2017_w01.pdf      0
 Kilinochchi  2021    53 2022-01-03 wer_2021_w53.pdf      9
 Kilinochchi  2022     1 2022-01-03 wer_2022_w01.pdf      9
  Kurunegala  2016    53 2017-01-02 wer_2016_w53.pdf     37
  Kurunegala  2017     1 2017-01-02 wer_2017_w01.pdf     80
  Kurunegala  2021    53 2022-01-03 wer_2021_w53.pdf     23
  Kurunegala  2022     1 2022-01-03 wer_2022_w01.pdf     23
      Mannar  2016    53 2017-01-02 wer_2016_w53.pdf      8
      Mannar  2017     1 2017-01-02 wer_2017_w01.pdf     37
      Mannar  2021    53 2022-01-03 wer_2021_w53.pdf     18
      Mannar  2022     1 2022-01-03 wer_2022_w01.pdf     18
      Matale  2016    53 2017-01-02 wer_2016_w53.pdf      4
      Matale  2017     1 2017-01-02 wer_2017_w01.pdf     25
      Matale  2021    53 2022-01-03 wer_2021_w53.pdf      4
      Matale  2022     1 2022-01-03 wer_2022_w01.pdf      4
      Matara  2016    53 2017-01-02 wer_2016_w53.pdf     38
      Matara  2017     1 2017-01-02 wer_2017_w01.pdf     73
      Matara  2021    53 2022-01-03 wer_2021_w53.pdf     31
      Matara  2022     1 2022-01-03 wer_2022_w01.pdf     31
  Monaragala  2016    53 2017-01-02 wer_2016_w53.pdf     17
  Monaragala  2017     1 2017-01-02 wer_2017_w01.pdf     21
  Monaragala  2021    53 2022-01-03 wer_2021_w53.pdf     14
  Monaragala  2022     1 2022-01-03 wer_2022_w01.pdf     14
  Mullaitivu  2016    53 2017-01-02 wer_2016_w53.pdf      1
  Mullaitivu  2017     1 2017-01-02 wer_2017_w01.pdf      1
  Mullaitivu  2021    53 2022-01-03 wer_2021_w53.pdf      0
  Mullaitivu  2022     1 2022-01-03 wer_2022_w01.pdf      0
Nuwara Eliya  2016    53 2017-01-02 wer_2016_w53.pdf      5
Nuwara Eliya  2017     1 2017-01-02 wer_2017_w01.pdf     12
Nuwara Eliya  2021    53 2022-01-03 wer_2021_w53.pdf      7
Nuwara Eliya  2022     1 2022-01-03 wer_2022_w01.pdf      7
 Polonnaruwa  2016    53 2017-01-02 wer_2016_w53.pdf     11
 Polonnaruwa  2017     1 2017-01-02 wer_2017_w01.pdf     11
 Polonnaruwa  2021    53 2022-01-03 wer_2021_w53.pdf      8
 Polonnaruwa  2022     1 2022-01-03 wer_2022_w01.pdf      8
    Puttalam  2016    53 2017-01-02 wer_2016_w53.pdf      2
    Puttalam  2017     1 2017-01-02 wer_2017_w01.pdf     18
    Puttalam  2021    53 2022-01-03 wer_2021_w53.pdf     90
    Puttalam  2022     1 2022-01-03 wer_2022_w01.pdf     90
   Ratnapura  2016    53 2017-01-02 wer_2016_w53.pdf     42
   Ratnapura  2017     1 2017-01-02 wer_2017_w01.pdf     63
   Ratnapura  2021    53 2022-01-03 wer_2021_w53.pdf     47
   Ratnapura  2022     1 2022-01-03 wer_2022_w01.pdf     47
 Trincomalee  2016    53 2017-01-02 wer_2016_w53.pdf     52
 Trincomalee  2017     1 2017-01-02 wer_2017_w01.pdf     22
 Trincomalee  2021    53 2022-01-03 wer_2021_w53.pdf     30
 Trincomalee  2022     1 2022-01-03 wer_2022_w01.pdf     30
    Vavuniya  2016    53 2017-01-02 wer_2016_w53.pdf      0
    Vavuniya  2017     1 2017-01-02 wer_2017_w01.pdf      0
    Vavuniya  2021    53 2022-01-03 wer_2021_w53.pdf      3
    Vavuniya  2022     1 2022-01-03 wer_2022_w01.pdf      3

[WARNING] Duplicate district/week observations detected (104 rows):
    district  year  week week_start      source_file  cases
      Ampara  2016    53 2017-01-02 wer_2016_w53.pdf      0
      Ampara  2017     1 2017-01-02 wer_2017_w01.pdf      5
      Ampara  2021    53 2022-01-03 wer_2021_w53.pdf      1
      Ampara  2022     1 2022-01-03 wer_2022_w01.pdf      2
Anuradhapura  2016    53 2017-01-02 wer_2016_w53.pdf      7
Anuradhapura  2017     1 2017-01-02 wer_2017_w01.pdf     16
Anuradhapura  2021    53 2022-01-03 wer_2021_w53.pdf     13
Anuradhapura  2022     1 2022-01-03 wer_2022_w01.pdf     13
     Badulla  2016    53 2017-01-02 wer_2016_w53.pdf     18
     Badulla  2017     1 2017-01-02 wer_2017_w01.pdf     40
     Badulla  2021    53 2022-01-03 wer_2021_w53.pdf     78
     Badulla  2022     1 2022-01-03 wer_2022_w01.pdf     78
  Batticaloa  2016    53 2017-01-02 wer_2016_w53.pdf     17
  Batticaloa  2017     1 2017-01-02 wer_2017_w01.pdf     43
  Batticaloa  2021    53 2022-01-03 wer_2021_w53.pdf     25
  Batticaloa  2022     1 2022-01-03 wer_2022_w01.pdf     25
     Colombo  2016    53 2017-01-02 wer_2016_w53.pdf    547
     Colombo  2017     1 2017-01-02 wer_2017_w01.pdf    511
     Colombo  2021    53 2022-01-03 wer_2021_w53.pdf     40
     Colombo  2022     1 2022-01-03 wer_2022_w01.pdf     40
       Galle  2016    53 2017-01-02 wer_2016_w53.pdf     79
       Galle  2017     1 2017-01-02 wer_2017_w01.pdf    176
       Galle  2021    53 2022-01-03 wer_2021_w53.pdf     44
       Galle  2022     1 2022-01-03 wer_2022_w01.pdf     44
     Gampaha  2016    53 2017-01-02 wer_2016_w53.pdf     44
     Gampaha  2017     1 2017-01-02 wer_2017_w01.pdf    137
     Gampaha  2021    53 2022-01-03 wer_2021_w53.pdf     43
     Gampaha  2022     1 2022-01-03 wer_2022_w01.pdf     43
  Hambantota  2016    53 2017-01-02 wer_2016_w53.pdf     26
  Hambantota  2017     1 2017-01-02 wer_2017_w01.pdf     31
  Hambantota  2021    53 2022-01-03 wer_2021_w53.pdf     25
  Hambantota  2022     1 2022-01-03 wer_2022_w01.pdf     25
      Jaffna  2016    53 2017-01-02 wer_2016_w53.pdf     57
      Jaffna  2017     1 2017-01-02 wer_2017_w01.pdf    145
      Jaffna  2021    53 2022-01-03 wer_2021_w53.pdf     74
      Jaffna  2022     1 2022-01-03 wer_2022_w01.pdf     74
    Kalmunai  2016    53 2017-01-02 wer_2016_w53.pdf     21
    Kalmunai  2017     1 2017-01-02 wer_2017_w01.pdf     90
    Kalmunai  2021    53 2022-01-03 wer_2021_w53.pdf     10
    Kalmunai  2022     1 2022-01-03 wer_2022_w01.pdf     10
    Kalutara  2016    53 2017-01-02 wer_2016_w53.pdf     77
    Kalutara  2017     1 2017-01-02 wer_2017_w01.pdf     88
    Kalutara  2021    53 2022-01-03 wer_2021_w53.pdf     20
    Kalutara  2022     1 2022-01-03 wer_2022_w01.pdf     20
       Kandy  2016    53 2017-01-02 wer_2016_w53.pdf     67
       Kandy  2017     1 2017-01-02 wer_2017_w01.pdf     66
       Kandy  2021    53 2022-01-03 wer_2021_w53.pdf     72
       Kandy  2022     1 2022-01-03 wer_2022_w01.pdf     72
     Kegalle  2016    53 2017-01-02 wer_2016_w53.pdf     22
     Kegalle  2017     1 2017-01-02 wer_2017_w01.pdf     34
     Kegalle  2021    53 2022-01-03 wer_2021_w53.pdf     42
     Kegalle  2022     1 2022-01-03 wer_2022_w01.pdf     42
 Kilinochchi  2016    53 2017-01-02 wer_2016_w53.pdf      8
 Kilinochchi  2017     1 2017-01-02 wer_2017_w01.pdf      0
 Kilinochchi  2021    53 2022-01-03 wer_2021_w53.pdf      9
 Kilinochchi  2022     1 2022-01-03 wer_2022_w01.pdf      9
  Kurunegala  2016    53 2017-01-02 wer_2016_w53.pdf     37
  Kurunegala  2017     1 2017-01-02 wer_2017_w01.pdf     80
  Kurunegala  2021    53 2022-01-03 wer_2021_w53.pdf     23
  Kurunegala  2022     1 2022-01-03 wer_2022_w01.pdf     23
      Mannar  2016    53 2017-01-02 wer_2016_w53.pdf      8
      Mannar  2017     1 2017-01-02 wer_2017_w01.pdf     37
      Mannar  2021    53 2022-01-03 wer_2021_w53.pdf     18
      Mannar  2022     1 2022-01-03 wer_2022_w01.pdf     18
      Matale  2016    53 2017-01-02 wer_2016_w53.pdf      4
      Matale  2017     1 2017-01-02 wer_2017_w01.pdf     25
      Matale  2021    53 2022-01-03 wer_2021_w53.pdf      4
      Matale  2022     1 2022-01-03 wer_2022_w01.pdf      4
      Matara  2016    53 2017-01-02 wer_2016_w53.pdf     38
      Matara  2017     1 2017-01-02 wer_2017_w01.pdf     73
      Matara  2021    53 2022-01-03 wer_2021_w53.pdf     31
      Matara  2022     1 2022-01-03 wer_2022_w01.pdf     31
  Monaragala  2016    53 2017-01-02 wer_2016_w53.pdf     17
  Monaragala  2017     1 2017-01-02 wer_2017_w01.pdf     21
  Monaragala  2021    53 2022-01-03 wer_2021_w53.pdf     14
  Monaragala  2022     1 2022-01-03 wer_2022_w01.pdf     14
  Mullaitivu  2016    53 2017-01-02 wer_2016_w53.pdf      1
  Mullaitivu  2017     1 2017-01-02 wer_2017_w01.pdf      1
  Mullaitivu  2021    53 2022-01-03 wer_2021_w53.pdf      0
  Mullaitivu  2022     1 2022-01-03 wer_2022_w01.pdf      0
Nuwara Eliya  2016    53 2017-01-02 wer_2016_w53.pdf      5
Nuwara Eliya  2017     1 2017-01-02 wer_2017_w01.pdf     12
Nuwara Eliya  2021    53 2022-01-03 wer_2021_w53.pdf      7
Nuwara Eliya  2022     1 2022-01-03 wer_2022_w01.pdf      7
 Polonnaruwa  2016    53 2017-01-02 wer_2016_w53.pdf     11
 Polonnaruwa  2017     1 2017-01-02 wer_2017_w01.pdf     11
 Polonnaruwa  2021    53 2022-01-03 wer_2021_w53.pdf      8
 Polonnaruwa  2022     1 2022-01-03 wer_2022_w01.pdf      8
    Puttalam  2016    53 2017-01-02 wer_2016_w53.pdf      2
    Puttalam  2017     1 2017-01-02 wer_2017_w01.pdf     18
    Puttalam  2021    53 2022-01-03 wer_2021_w53.pdf     90
    Puttalam  2022     1 2022-01-03 wer_2022_w01.pdf     90
   Ratnapura  2016    53 2017-01-02 wer_2016_w53.pdf     42
   Ratnapura  2017     1 2017-01-02 wer_2017_w01.pdf     63
   Ratnapura  2021    53 2022-01-03 wer_2021_w53.pdf     47
   Ratnapura  2022     1 2022-01-03 wer_2022_w01.pdf     47
 Trincomalee  2016    53 2017-01-02 wer_2016_w53.pdf     52
 Trincomalee  2017     1 2017-01-02 wer_2017_w01.pdf     22
 Trincomalee  2021    53 2022-01-03 wer_2021_w53.pdf     30
 Trincomalee  2022     1 2022-01-03 wer_2022_w01.pdf     30
    Vavuniya  2016    53 2017-01-02 wer_2016_w53.pdf      0
    Vavuniya  2017     1 2017-01-02 wer_2017_w01.pdf      0
    Vavuniya  2021    53 2022-01-03 wer_2021_w53.pdf      3
    Vavuniya  2022     1 2022-01-03 wer_2022_w01.pdf      3
[clean] drop duplicate (district, week_start): 26441 → 26389 rows (Δ 52)
[clean] total: 26441 → 26389 rows (Δ 52)

,district,source_file,week_ending,epi_week,year,dengue_fever_this_week,dengue_fever_cumulative,dysentery_this_week,dysentery_cumulative,encephalitis_this_week,...,leishmaniasis_cumulative,timeliness_pct,completeness_pct,tuberculosis_this_week,tuberculosis_cumulative,leprosy_this_week,leprosy_cumulative,cases,week,week_start
0,Ampara,wer_2007_w01.pdf,2006-12-29,52,2007,0,33,2,263,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,2007-01-01
1,Ampara,wer_2007_w02.pdf,2007-01-05,1,2007,0,0,2,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2,2007-01-08
2,Ampara,wer_2007_w03.pdf,2007-01-12,2,2007,0,0,1,4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3,2007-01-15
3,Ampara,wer_2007_w04.pdf,2007-01-19,3,2007,0,0,2,14,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,4,2007-01-22
4,Ampara,wer_2007_w05.pdf,2007-01-26,4,2007,0,0,0,16,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5,2007-01-29

In [9]:
clean.shape

(26389, 39)